accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'accounts'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('change_password', change_password, name='change_password'),
    path('profile/<int:pk>', get_profile, name='profile', kwargs={'app_name': app_name, 'app_category_name': '개인정보', 'page_name': '프로필'}),
    path('profile/upload_img', upload_profile_image, name='upload_profile_image'),
    path('profile/clear_img', clear_profile_image, name='clear_profile_image')
]

mdm/urls.py
from django.urls import path, re_path
from mdm.views import *

from mdm.views.eval_plan import get_all_evaluation_plan, get_detail_eval_plan, save_eval_plan, del_eval_plan

app_name = 'mdm'
app_category_name = '기준정보 관리'

urlpatterns = [
    # 평가지 관리 메인 이동
    path('esheet/', sheet, name='eval_sheet',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가지관리'}),
    path('esheet/modal', modal, name="modal"),
    path('esheet/eval_ques', eval_ques_delete, name="eval_ques_delete"),
    path('esheet/eval_sheet', create_eval_sheet, name="eval_sheet_add"),

    # 평가항목 관리 메인 이동
    path('eitem/', get_all_evaluation_item, name='eval_item',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가항목관리'}),

    # 평가계획 관리 메인 이동
    path('eplan/', get_all_evaluation_plan, name='eval_plan',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가계획관리'}),
    
    # 비동기 요청
    path('ajax/test/', ajax_sample, name='ajax_sample'),
    path('eplan/detail/', get_detail_eval_plan, name='eplan_detail'),
    path('eplan/save', save_eval_plan, name='eplan_save'),

    # 평가문항 관리 메인 이동
    path('eques/', get_all_question, name='eval_ques', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가문항관리'}),
    path('eques/add', ajax_add_question, name='add_question'),
    path('eques/ques', get_question, name='get_question'),
    path('eques/save', save_question, name='save_question'),
    path('eques/eitem', ajax_get_eval_item, name='get_eval_item'),
    path('eplan/save/', save_eval_plan, name='eplan_save'),
    path('eplan/del/', del_eval_plan, name='eplan_del'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin, Group
)


class MemberManager(BaseUserManager):
    def create_user(self, username, password, name):
        member = self.model(
            name=name,
            password='dbzmfflem1!',
            email=self.normalize_email(username),
            username=username,
        )

        member.set_password(password)
        member.save(using=self._db)
        return member

    def create_superuser(self, username, password, name):
        user = self.create_user(
            password=password,
            name=name,
            email=username,
            username=username,
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def save(self, *args, **kwargs):
        print("=====")
        print("저장")
        print("=====")
        user = super().save(commit=False)
        if self.cleaned_data["password"] is None:
            user.set_password('dbzmfflem1!')
        else:
            user.set_password(self.cleaned_data["password"])

        user.save()
        return user


class EusoMem(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(db_column='id', primary_key=True, verbose_name='아이디')
    username = models.CharField(max_length=150, unique=True, blank=True, null=True, verbose_name="로그인ID")
    password = models.CharField(max_length=128, blank=True, null=True, verbose_name="비밀번호")
    email = models.EmailField(max_length=50, unique=True, null=False, verbose_name='이메일')
    name = models.CharField(max_length=50, verbose_name="사원명")
    is_superuser = models.BooleanField(default=False, verbose_name="시스템관리자 여부")
    is_staff = models.BooleanField(default=False)
    last_login = models.DateTimeField(blank=True, null=True)
    posi_cd = models.CharField(max_length=20, blank=True, null=True)
    duty_resp_cd = models.CharField(max_length=20, blank=True, null=True)
    dept_no = models.IntegerField(db_column='dept_no', blank=True, null=True)
    zip_no = models.CharField(max_length=50, blank=True, null=True)
    mem_addr = models.CharField(max_length=100, blank=True, null=True)
    join_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    mem_stat_cd = models.CharField(max_length=20, blank=True, null=True, verbose_name="회원상태코드")
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    del_yn = models.CharField(max_length=1, blank=True, null=True, default='N', verbose_name="삭제여부")
    is_staff = models.BooleanField(default=False, verbose_name="시스템관리자 여부")
    profile_img = models.ImageField(upload_to='profile')
    objects = MemberManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name', ]

    class Meta:
        managed = False
        db_table = 'euso_mem'
        verbose_name = '사원'
        ordering = ['-join_dt']

accounts/views.py
from django.shortcuts import render
from django.views.generic import FormView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from .models import EusoMem
from django.contrib import auth
from management.models import CommCd
from django.contrib.auth.hashers import check_password
from uuid import uuid4
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_profile(request, pk, *args, **kwargs):
    qs = EusoMem.objects.get(pk=pk)

    return render(request, "profile/profile.html", {'mem_detail': qs, **kwargs})


@api_view(['GET', 'POST'])
@permission_classes([AllowAny])
def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            posi_nm = CommCd.objects.get(comm_cd=user.posi_cd).cd_nm
            duty_resp_nm = CommCd.objects.get(comm_cd=user.duty_resp_cd).cd_nm

            request.session['posi_nm'] = posi_nm
            request.session['duty_resp_nm'] = duty_resp_nm
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, "auth/login.html", {'error': "회원ID와 비밀번호가 일치하지 않습니다."})
    else:
        return render(request, 'auth/login.html')

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def change_password(request):
    param = request.data.copy()
    print(param)
    result = dict()
    current_password = param['origin_password']
    user = request.user
    if check_password(current_password, user.password):
        new_password = param['password_1']
        password_confirm = param['password_2']
        if new_password == password_confirm:
            user.set_password(new_password)
            user.save()
            auth.login(request, user)
            result.update(is_error=False, msg='비밀번호 변경에 성공하였습니다.')
        else:
            result.update(is_error=True, target='password1', msg='비밀번호와 확인 비밀번호가 일치하지 않습니다.')
    else:
       result.update(is_error=True, target='origin_password', msg='현재 비밀번호와 일치하지 않습니다.')
    return JsonResponse(result)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def upload_profile_image(request):
    result = dict(is_success=False)
    if request.FILES:

        profile_img = request.FILES['profile_img']
        user = request.user
        user_qs = EusoMem.objects.get(pk=user.id)

        uuid = uuid4().hex
        ext = profile_img.name.split('.')[-1]

        filename = '{}.{}'.format(uuid, ext)

        profile_img.name = filename

        user_qs.profile_img = profile_img

        user_qs.save()
        result.update(is_success=True)
    return JsonResponse(result)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def clear_profile_image(request):
    user = request.user
    user_qs = EusoMem.objects.get(pk=user.id)
    user_qs.profile_img = None

    user_qs.save()
    result = dict(is_success=True)
    return JsonResponse(result)


def logout(request):
    auth.logout(request)
    return redirect('main')

accounts/templates/profile/profile.html
{% extends "_layout.html" %}
{% load static %}
{% load common_tags %}
{% block content %}

    <div class="row">
        <div class="col-md-3">
            {% include 'profile/profile_basic.html' %}
        </div>
        <div class="col-md-9">

            {% include 'profile/profile_detail.html' %}
        </div>
    </div>

{% endblock %}

accounts/templates/profile/profile_basic.html
{% load static %}
{% load common_tags %}

<div class="box box-primary">
    <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle"
                {% if mem_detail.profile_img %}
             src="{{ mem_detail.profile_img.url|default:'' }}"
                {% else %}
             src="/media/profile/default_avatar.png"
                {% endif %}
             alt="프로필 사진">

        <form id="profile_image_form">
            {% csrf_token %}
            <input type="file" name="profile_img" id="profile_img" style="display: none" ;
                   onchange="uploadProfileImage(this)"/>
        </form>
        <h3 class="profile-username text-center">{{ mem_detail.name }}</h3>

        <p class="text-muted text-center">{{ mem_detail.username }}</p>
        <div class="text-center">
            <a class="btn btn-primary" onclick="document.getElementById('profile_img').click()"><b>프로필사진
                변경</b></a>
            <a onclick="clearProfileImage()" class="btn btn-default"><b>초기화</b></a>
        </div>
        <br/>
        <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
                <b>부서</b> <label class="pull-right">{{ mem_detail.dept_no | get_dept_nm }}</label>
            </li>
            <li class="list-group-item">

                <b>직급</b> <label class="pull-right">{{ mem_detail.posi_cd | get_code_nm }} </label>
            </li>
            <li class="list-group-item">
                <b>직책</b> <label class="pull-right">{{ mem_detail.duty_resp_cd | get_code_nm }}</label>
            </li>
        </ul>


    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

<!-- About Me Box -->
{#<div class="box box-primary">#}
{#    <div class="box-header with-border">#}
{#        <h3 class="box-title">About Me</h3>#}
{#    </div>#}
{#    <!-- /.box-header -->#}
{#    <div class="box-body">#}
{#        <strong><i class="fa fa-book margin-r-5"></i> Education</strong>#}
{##}
{#        <p class="text-muted">#}
{#            B.S. in Computer Science from the University of Tennessee at Knoxville#}
{#        </p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>#}
{##}
{#        <p class="text-muted">Malibu, California</p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>#}
{##}
{#        <p>#}
{#            <span class="label label-danger">UI Design</span>#}
{#            <span class="label label-success">Coding</span>#}
{#            <span class="label label-info">Javascript</span>#}
{#            <span class="label label-warning">PHP</span>#}
{#            <span class="label label-primary">Node.js</span>#}
{#        </p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>#}
{##}
{#        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>#}
{#    </div>#}
{#    <!-- /.box-body -->#}
{#</div>#}

<script>
    function clearProfileImage(target) {

        swal({
            text: "이미 등록된 프로필 사진을 삭제하고 초기화 하시겠습니까?",
            icon: "info",
            buttons: {
                cancle: {
                    text: "취소",
                    value: null,
                    className: "swal-button--cancel",
                    closeModal: true,
                },
                confir: {
                    text: "확인",
                    value: true,
                    closeModal: true,
                }
            },
        }).then((value) => {
            if (value) {
                let formData = new FormData();
                formData.append("csrfmiddlewaretoken", '{{ csrf_token }}')
                $.ajax({
                    url: "{% url 'accounts:clear_profile_image' %}",
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (response) {
                        swal({
                            text: "프로필사진이 변경되었습니다.",
                            icon: "success"
                        }).then((value) => {
                            location.replace(location.href);
                        })

                    },
                    error: function (response) {
                        swal({
                            text: "프로필변경에 실패하였습니다. 다시 시도해주세요.",
                            icon: "error"
                        })
                    }
                })
            }
        })


    }

    function uploadProfileImage(target) {
        let filesArr = Array.prototype.slice.call(target.files);

        const reg = /(.*?)\/(jpg|jpeg|png|bmp)$/;

        filesArr.forEach(function (file) {
            if (!file.type.match(reg)) {
                alert("이미지 확장자만 업로드 가능합니다.");
                return;
            }
        })

        let data = new FormData($('#profile_image_form').get(0));
        $.ajax({
            url: "{% url 'accounts:upload_profile_image' %}",
            type: "POST",
            processData: false,
            contentType: false,
            data: data,
            success: function (response) {
                if (response.is_success) {
                    swal({
                        text: "프로필사진이 변경되었습니다.",
                        icon: "success"
                    }).then((value) => {
                        location.replace(location.href);
                    })
                } else {
                    swal({
                        text: "프로필변경에 실패하였습니다. 다시 시도해주세요.",
                        icon: "error"
                    })
                }
            },
            error: function (response) {
                swal({
                    text: "프로필변경에 실패하였습니다. 다시 시도해주세요.",
                    icon: "error"
                })
            }

        })
    }
</script>

accounts/templates/profile/profile_detail.html
{% load static %}
{% load common_tags %}

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#personal_info" data-toggle="tab">개인정보</a></li>
        <li><a href="#project_history" data-toggle="tab">프로젝트 이력</a></li>

    </ul>
    <div class="tab-content">

        <div class="tab-pane active" id="personal_info">
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Email(ID)</label>

                    <div class="col-sm-10">
                        <span class="form-control" style="border:none;">{{ mem_detail.username }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">이름</label>

                    <div class="col-sm-10">
                        <span class="form-control" style="border:none;">{{ mem_detail.name }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">비밀번호</label>

                    <div class="col-sm-10">
                        <button type="button" data-toggle="modal" data-target="#change-password-modal"
                                class="btn btn-default">비밀번호 변경
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">주소</label>

                    <div class="col-sm-10">
                                    <span class="form-control"
                                          style="border:none;">{{ mem_detail.mem_addr|default:'' }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">가입일</label>

                    <div class="col-sm-10">
                                    <span class="form-control"
                                          style="border:none;">{{ mem_detail.join_dt|default:'' }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputExperience" class="col-sm-2 control-label">재직구분</label>

                    <div class="col-sm-10">
                                    <span class="form-control"
                                          style="border:none;">{{ mem_detail.mem_stat_cd|get_code_nm }}</span>
                    </div>
                </div>
            </form>
            {% include 'auth/change_password_modal.html' %}
            <hr/>
            <div>
                <h4>취득 자격증정보</h4>
                <div class="table-responsive" style="overflow: auto; max-height: 150px;">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>자격증명</th>
                            <th>기관</th>
                            <th>취득일</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>


                        </tbody>
                    </table>
                </div>
            </div>
            <hr/>
            <div>
                <h4>이수 교육정보</h4>
                <div class="table-responsive" style="overflow: auto; max-height: 150px;">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>교육과정명</th>
                            <th>기관</th>
                            <th>이수일</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="4">
                                데이터 준비중입니다.
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <hr/>

        </div>

        <!-- /.tab-pane -->
        <div class="tab-pane" id="project_history">
            <div>
                <h4>참여 프로젝트정보</h4>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>프로젝트명</th>
                        <th>기관</th>
                        <th>기간</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="text-center" colspan="4">
                            데이터 준비중입니다.
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.tab-pane -->


        <!-- /.tab-pane -->
    </div>
    <!-- /.tab-content -->
</div>