management/urls.py
from django.urls import path, re_path
from management.views.pjt import (
    get_all_pjt, get_join_pjt_member, create_pjt_join_hist_member, delete_pjt_join_hist_member, create_pjt
    )
from management.views import code, code_list, code_add

app_name = 'management'

urlpatterns = [
    path('pjt/', get_all_pjt, name='pjt_list'),
    path('code/', code, name='code'),
    path('code/list', code_list, name='code_list'),
    path('code/add', code_add, name='code_add'),




    # ajax api
    path('pjtJoin/create/', create_pjt_join_hist_member, name='create_pjt_join_hist'),
    path('pjtJoin/delete/', delete_pjt_join_hist_member, name='del_pjt_join_hist'),
    path('pjtJoin/', get_join_pjt_member, name='join_pjt_mem'),
    path('pjt/create/', create_pjt, name='create_pjt')
    ]

mdm/urls.py
from django.urls import path, re_path
from mdm.views import *

from mdm.views.eval_plan import get_all_evaluation_plan, get_detail_eval_plan, save_eval_plan, del_eval_plan

app_name = 'mdm'
app_category_name = '기준정보 관리'

urlpatterns = [
    # 평가지 관리 메인 이동
    path('esheet/', sheet, name='eval_sheet',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가지관리'}),
    path('esheet/modal', modal, name="modal"),
    path('esheet/eval_ques', eval_ques_delete, name="eval_ques_delete"),
    path('esheet/eval_sheet', create_eval_sheet, name="eval_sheet_add"),

    # 평가항목 관리 메인 이동
    path('eitem/', get_all_evaluation_item, name='eval_item',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가항목관리'}),

    # 평가계획 관리 메인 이동
    path('eplan/', get_all_evaluation_plan, name='eval_plan',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가계획관리'}),
    
    # 비동기 요청
    path('ajax/test/', ajax_sample, name='ajax_sample'),
    path('eplan/detail/', get_detail_eval_plan, name='eplan_detail'),
    path('eplan/save', save_eval_plan, name='eplan_save'),

    # 평가문항 관리 메인 이동
    path('eques/', get_all_question, name='eval_ques', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가문항관리'}),
    path('eques/add', ajax_add_question, name='add_question'),
    path('eques/ques', get_question, name='get_question'),
    path('eques/save', save_question, name='save_question'),
    path('eques/eitem', ajax_get_eval_item, name='get_eval_item'),
    path('eplan/save/', save_eval_plan, name='eplan_save'),
    path('eplan/del/', del_eval_plan, name='eplan_del'),


]

management/models.py
from django.db import models
from accounts.models import EusoMem


# Create your models here.
class CommCd(models.Model):
    comm_cd = models.CharField(primary_key=True, max_length=10)
    hi_comm_cd = models.CharField(max_length=10, blank=True, null=True)
    cd_nm = models.CharField(max_length=100)
    cd_desc = models.CharField(max_length=200, blank=True, null=True)
    etc_1 = models.CharField(max_length=100, blank=True, null=True)
    etc_2 = models.CharField(max_length=100, blank=True, null=True)
    etc_3 = models.CharField(max_length=100, blank=True, null=True)
    alias_cd = models.CharField(max_length=10, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comm_cd'


class ZipCd(models.Model):
    zip_no = models.CharField(primary_key=True, max_length=6)
    sido = models.CharField(max_length=20, blank=True, null=True)
    sigungu = models.CharField(max_length=20, blank=True, null=True)
    eupmyun = models.IntegerField(blank=True, null=True)
    doro_cd = models.IntegerField(blank=True, null=True)
    doro_nm = models.CharField(max_length=80, blank=True, null=True)
    build_no1 = models.IntegerField(blank=True, null=True)
    build_no2 = models.IntegerField(blank=True, null=True)
    build_nm = models.CharField(max_length=200, blank=True, null=True)
    dong_cd = models.CharField(max_length=10, blank=True, null=True)
    dong_nm = models.CharField(max_length=20, blank=True, null=True)
    ri = models.CharField(max_length=20, blank=True, null=True)
    h_dong_nm = models.CharField(max_length=20, blank=True, null=True)
    zibun1 = models.IntegerField(blank=True, null=True)
    zibun2 = models.IntegerField(blank=True, null=True)
    zip_no_old = models.CharField(max_length=6, blank=True, null=True)
    zip_sn = models.CharField(max_length=3, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True)
    modf_dt = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'zip_cd'


class CsOrgn(models.Model):
    cs_no = models.AutoField(primary_key=True)
    zip_no = models.ForeignKey('ZipCd', models.DO_NOTHING, blank=True, null=True, db_column='zip_no')
    cs_nm = models.CharField(max_length=100, blank=True, null=True)
    orgn_reg_no = models.CharField(max_length=13, blank=True, null=True)
    busir_no = models.CharField(max_length=10, blank=True, null=True)
    tel_no = models.CharField(max_length=12, blank=True, null=True)
    fax_no = models.CharField(max_length=12, blank=True, null=True)
    cs_addr = models.CharField(max_length=100, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'cs_orgn'


class EusoPjt(models.Model):
    pjt_no = models.AutoField(primary_key=True)
    cs_no = models.ForeignKey(CsOrgn, models.DO_NOTHING, db_column='cs_no')
    pjt_nm = models.CharField(max_length=100, blank=True, null=True)
    start_dt = models.DateField(max_length=8, blank=True, null=True)
    end_dt = models.DateField(max_length=8, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'euso_pjt'


class PjtJoinHist(models.Model):
    join_hist_no = models.AutoField(primary_key=True)
    pjt_no = models.ForeignKey(EusoPjt, models.DO_NOTHING, db_column='pjt_no')
    mem_no = models.ForeignKey(EusoMem, models.DO_NOTHING, db_column='mem_no')
    role_cd = models.CharField(max_length=10, blank=True, null=True)
    enter_dt = models.DateField(max_length=8, blank=True, null=True)
    out_dt = models.DateField(max_length=8, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    del_yn = models.CharField(max_length=1, default='N', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'pjt_join_hist'


class EusoDept(models.Model):
    dept_no = models.AutoField(primary_key=True)
    dept_cd = models.CharField(max_length=10, blank=True, null=True)
    hi_dept_no = models.IntegerField(blank=True, null=True)
    dept_nm = models.CharField(max_length=50, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True, verbose_name='등록 회원ID')
    modf_mem_no = models.IntegerField(blank=True, null=True, verbose_name='수정자 ID')
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    del_yn = models.CharField(max_length=1, blank=True, null=True)


    class Meta:
        managed = True
        db_table = 'euso_dept'
        verbose_name = '부서'

management/views/code.py
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser
from django.shortcuts import render, redirect
from rest_framework.response import Response
from django.urls import reverse
from management.serializers import *


@api_view(['POST', 'GET', 'DELETE'])
@permission_classes([IsAuthenticated, IsAdminUser])
@csrf_exempt
def code(req):
    test = req.data.copy()
    test['reg_mem_no'] = req.user.id
    if req.method == 'GET':
        codes = CommCd.objects.all()
        # codes = ABCD.objects.filter(del_yn='N')
        serializer = CommCdSerializer(codes, many=True)
        listt = {
            'comm_cd': "",
        }
        return render(req, 'code/common_code.html', {'code_list': serializer.data, 'list': listt})
    if req.method == 'DELETE':
        try:
            old_id = test['comm_cd']
            print(test)
            test['modf_mem_no'] = req.user.id
            obj = CommCd.objects.get(comm_cd=old_id)
            serializer = CommCdSerializer(obj, data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            req.method = 'GET'
            return Response(status=status.HTTP_204_NO_CONTENT)
        except:
            return Response(status=status.HTTP_410_GONE)

    if req.method == 'POST':
        try:
            old_id = test['comm_cd']
            test['modf_mem_no'] = req.user.id

            obj = CommCd.objects.get(comm_cd=old_id)  # 존재하지않으면 doesnotexist 예외처리 -> except구문
            # obj가 존재하는 경우 == 이미 있는 코드 => 수정 로직
            serializer = CommCdSerializer(obj, data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            return redirect(reverse('management:code'), req)
        except:
            test['modf_mem_no'] = req.user.id

            serializer = CommCdSerializer(data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            return redirect(reverse('management:code'), req)


@api_view(['GET'])
@permission_classes([IsAuthenticated, IsAdminUser])
@csrf_exempt
def code_list(req):
    comm_cd = req.GET['comm_cd']
    data = CommCd.objects.filter(comm_cd=comm_cd)
    serializer = CommCdSerializer(data, many=True)
    return render(req, 'code/code_put.html', {'list': serializer.data, })


@api_view(['GET'])
@permission_classes([IsAuthenticated, IsAdminUser])
def code_add(req):
    listt = {
        'comm_cd': "",
    }
    return render(req, 'code/code_put.html', {'list': listt})

management/views/pjt.py
from rest_framework import status
from datetime import datetime
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.shortcuts import render, redirect

from management.models import EusoPjt, CommCd, PjtJoinHist, CsOrgn
from accounts.models import EusoMem

from management.serializers import (
    EusoPjtSerializer, CommCdMapperSerializer, GetPjtJoinMemberSerializer, CreatePjtJoinMemberSerializer,
    DelPjtJoinMemberSerializer, GetCsOrgnSerializer, CreatePjtSerializer
    )
from accounts.serializers import GetEusoMemSerializer


@api_view(['GET'])
@permission_classes([AllowAny])
def get_all_pjt(requests):
    # 프로젝트 목록 가져오기
    pjt_obj = EusoPjt.objects.all().order_by('-start_dt')
    pjt_serializer = EusoPjtSerializer(pjt_obj, many=True)

    # 기관 목록 가져오기
    cs_obj = CsOrgn.objects.filter(del_yn='N')
    cs_serializer = GetCsOrgnSerializer(cs_obj, many=True)
    return render(requests, 'pjt/pjt_main.html', {'pjt_list': pjt_serializer.data, 'cs_ls': cs_serializer.data})


@api_view(['POST'])
@permission_classes([AllowAny])
def create_pjt(requests):
    req = requests.data

    date_range = [date.strip() for date in req['date_range'].split('-')]
    start_dt = datetime.strptime(date_range[0], '%m/%d/%Y')
    end_dt = datetime.strptime(date_range[1], '%m/%d/%Y')

    pjt_dic = {
        "pjt_nm": req["pjt_nm"],
        "cs_no": req["cs_no"],
        "start_dt": start_dt,
        "end_dt": end_dt,
        "reg_mem_no": requests.user.id,
        "modf_mem_no": requests.user.id
    }
    pjt_serializer = CreatePjtSerializer(data=pjt_dic)
    if pjt_serializer.is_valid():
        pjt_serializer.save()

        return redirect("/manage/pjt/")

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_serializer.errors})


@api_view(["POST", "GET"])
@permission_classes([AllowAny])
def get_join_pjt_member(requests):
    pjt_no = requests.data["pjt_no"]

    # 회원 목록 가져오기
    euso_mem_qs = EusoMem.objects.filter(del_yn="N")
    euso_mem_serializer = GetEusoMemSerializer(euso_mem_qs, many=True)

    # 프로젝트 역할 코드 가져오기
    role_cd_qs = CommCd.objects.filter(hi_comm_cd='CC004000', del_yn='N')
    role_cd_serializer = CommCdMapperSerializer(role_cd_qs, many=True)

    # 프로젝트 참여중인 회원 목록 가져오기
    pjt_join_hist_qs = PjtJoinHist.objects.filter(pjt_no=pjt_no, del_yn='N')
    pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_qs, many=True)
    return render(requests, 'pjt/pjt_join_mem.html', {'role_list': role_cd_serializer.data,
                                                     'pjt_no': pjt_no,
                                                     'mem_ls': euso_mem_serializer.data,
                                                     'pjt_mem_ls': pjt_join_hist_serializer.data,
                                                     })


@api_view(["POST"])
@permission_classes([AllowAny])
def create_pjt_join_hist_member(requests):
    req = requests.data.copy()

    date_range = [date.strip() for date in req['date_range'].split('-')]
    enter_dt = datetime.strptime(date_range[0], '%m/%d/%Y').strftime("%Y-%m-%d")
    out_dt = datetime.strptime(date_range[1], '%m/%d/%Y').strftime("%Y-%m-%d")

    print(enter_dt)
    print(out_dt)

    pjt_join_hist_dic = {
        "pjt_no": req['pjt_no'],
        "mem_no": req['mem_no'],
        "role_cd": req['role_cd'],
        "enter_dt": enter_dt,
        "out_dt": out_dt,
        "reg_mem_no": requests.user.id,
        "modf_mem_no": requests.user.id
    }

    pjt_join_hist_serializer = CreatePjtJoinMemberSerializer(data=pjt_join_hist_dic)
    if pjt_join_hist_serializer.is_valid():
        pjt_join_hist_serializer.save()

        # 프로젝트 참여중인 회원 목록 가져오기
        pjt_join_hist_obj = PjtJoinHist.objects.filter(pjt_no=req['pjt_no'], del_yn='N')
        pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_obj, many=True)
        return render(requests, 'pjt/pjt_mem_ls_form.html', {"pjt_mem_ls": pjt_join_hist_serializer.data})

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_join_hist_serializer.errors})


@api_view(["POST"])
@permission_classes([AllowAny])
def delete_pjt_join_hist_member(requests):
    req = requests.data.copy()

    pjt_join_hist_dic = {
        "join_hist_no": req['join_hist_no'],
        "mem_no": req['mem_no'],
        "del_yn": "Y",
        "modf_mem_no": requests.user.id
    }

    pjt_join_hist_qs = PjtJoinHist.objects.get(join_hist_no=req['join_hist_no'])
    pjt_join_hist_serializer = DelPjtJoinMemberSerializer(pjt_join_hist_qs, data=pjt_join_hist_dic)

    if pjt_join_hist_serializer.is_valid():
        pjt_join_hist_serializer.save()

        # 프로젝트 참여중인 회원 목록 가져오기
        pjt_join_hist_qs = PjtJoinHist.objects.filter(pjt_no=req['pjt_no'], del_yn='N')
        pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_qs, many=True)
        return render(requests, 'pjt/pjt_mem_ls_form.html', {"pjt_mem_ls": pjt_join_hist_serializer.data})

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_join_hist_serializer.errors})

management/templates/code/code_list.html
{% block content %}

    <body class="hold-transition skin-blue sidebar-mini">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">

                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div><div  class="pull-right add">
                        <button  id="add"style="cursor: pointer" type="button" class="btn btn-primary btn-sm">추가
                        </button>

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>공통 코드</th>
                                <th>상위 코드</th>
                                <th>코드 이름</th>
                                <th>코드 상세</th>
                                <th>비고 1</th>
                                <th>비고 2</th>
                                <th>비고 3</th>
                                <th>대체 코드</th>
                                <th>삭제 여부</th>

                            </tr>
                            </thead>

                            <tbody>
                            {% for code in code_list %}
                                
                                <tr style="cursor: pointer" class="ctr">
                                    <td id="{{ code.comm_cd }}">{{ code.comm_cd }}</td>
                                    <td>{{ code.hi_comm_cd|default:"" }}</td>
                                    <td>{{ code.cd_nm }}</td>
                                    <td>{{ code.cd_desc|default:"" }}</td>
                                    <td>{{ code.etc_1|default:"" }}</td>
                                    <td>{{ code.etc_2|default:"" }}</td>
                                    <td>{{ code.etc_3|default:"" }}</td>
                                    <td>{{ code.alias_cd|default:"" }}</td>
                                    <td>{{ code.del_yn }}</td>

                                </tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th>공통 코드</th>
                                <th>상위 코드</th>
                                <th>코드 이름</th>
                                <th>코드 상세</th>
                                <th>비고 1</th>
                                <th>비고 2</th>
                                <th>비고 3</th>
                                <th>대체 코드</th>
                                <th>삭제 여부</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    {#                    <!-- /.box-body -->#}
                </div>
                <!-- /.box -->

                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- jQuery 2.2.3 -->
    <script src="../../../static/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="../../../static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="../../../static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../../static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="../../../static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="../../../static/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="../../../static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../../static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>

        $('.ctr').on("click", row_select);
        $('#add').on("click", add_comm_cd);

        function add_comm_cd() {
            $.ajax({
                url: "{% url 'management:code_add' %}",
                type: "GET",
                datatype: "json",

                success: function (data) {
                    $(".box-primary").html(data)
                }
            })
        }

        function row_select() {
            $.ajax({
                url: "{% url 'management:code_list' %}",
                type: "GET",
                datatype: "json",
                data: {
                    'comm_cd': $(this).children().first()[0].id,
                },
                success: function (data) {
                    $(".box-primary").html(data)
                }
            })
        }

        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
    </script>
    </body>
{% endblock %}

management/templates/code/code_put.html
{% load static %}
<script>
    $.ajaxSetup({
        headers: {"X-CSRFToken": '{{csrf_token}}'}
    });

    function delete_ajax() {
        const csrf_token = jQuery("[name=csrfmiddlewaretoken]").val();
        $.ajax({
            url: "{% url 'management:code'%}",
            type: "DELETE",
            datatype: "json",
            data: {
                'comm_cd': $("#comm_cd").val(),
                'hi_comm_cd': $("#hi_comm_cd").val(),
                'cd_nm': $("#cd_nm").val(),
                'cd_desc': $("#cd_desc").val(),
                'etc_1': $("#etc_1").val(),
                'etc_2': $("#etc_2").val(),
                'etc_3': $("#etc_3").val(),
                'alias_cd': $("#alias_cd").val(),
                'del_yn': "Y"
            },
            success: function (data) {
                swal({
                    icon: "success",
                    title: "공통코드가 삭제되었습니다."
                })
                    .then(()=>{
                        window.location.reload()
                    })
            }
        })
    }

    function save_ajax() {
        if($("#cd_nm").val() == ""){
            swal({
                icon:"warning",
                title:"코드 이름을 입력해주세요."
            })
            return;
        }
        $.ajax({
            url: "{% url 'management:code' %}",
            type: "POST",
            datatype: "json",
            data: {
                "csrfmiddlewaretoken": $("#token").children(1).val(),
                'comm_cd': $("#comm_cd").val(),
                'hi_comm_cd': $("#hi_comm_cd").val(),
                'cd_nm': $("#cd_nm").val(),
                'cd_desc': $("#cd_desc").val(),
                'etc_1': $("#etc_1").val(),
                'etc_2': $("#etc_2").val(),
                'etc_3': $("#etc_3").val(),
                'alias_cd': $("#alias_cd").val(),
                'del_yn': $("#del_yn").val(),

            },
            success: function (data) {
                swal({
                    icon: "success",
                    title: "공통코드가 생성되었습니다."
                }).then(() => {
                    window.location.reload();

                })


            }
        })
    }
</script>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">공통 코드 상세정보</h3>
        {#        <form action={% url 'management:code' %}  method="POST" role="form">#}
        <div id="token">
            {% csrf_token %}

        </div>

        <div class="box-tools pull-right">
            <div class="btn-group">

                {#                                        <input type ="submit" class="btn btn-default btn-sm" value="수정"></input>#}
                <button type="button" class="btn btn-default btn-sm" onclick="save_ajax()">저장</button>
                <button type="button" class="btn btn-danger btn-sm" onclick="delete_ajax()">삭제</button>
                {#                                        <input type="submit" class="btn btn-danger btn-sm" value="삭제"></input>#}
            </div>
        </div>
        <!-- /.box-tools -->

        {% for code in list %}

            <div class="box-body">
                <div class="form-group">
                    <label for="comm_cd">공통 코드</label>
                    <input type="text" name="comm_cd" class="form-control" id="comm_cd" placeholder="공통코드 입력"
                           value="{{ code.comm_cd }}">
                </div>
                <div class="form-group">
                    <label for="hi_comm_cd">상위 코드</label>
                    <input name="hi_comm_cd" class="form-control" id="hi_comm_cd" placeholder="상위코드 입력"
                           value="{{ code.hi_comm_cd }}">
                </div>
                <label for="cd_nm">코드 이름</label>
                <input name="cd_nm" class="form-control" id="cd_nm" placeholder="코드 이름 입력" value="{{ code.cd_nm }}">
            </div>
            <div class="form-group">
                <label for="cd_desc">코드 상세</label>
                <input name="cd_desc" class="form-control" id="cd_desc" placeholder="코드 상세 입력"
                       value="{{ code.cd_desc }}">
            </div>
            <div class="form-group">
                <label for="etc_1">비고 1</label>
                <input name="etc_1" class="form-control" id="etc_1" placeholder="비고 1 입력" value="{{ code.etc_1 }}">
            </div>
            <div class="form-group">
                <label for="etc_2">비고 2</label>
                <input name="etc_2" class="form-control" id="etc_2" placeholder="비고 2 입력" value="{{ code.etc_2 }}">
            </div>
            <div class="form-group">
                <label for="etc_3">비고 3</label>
                <input name="etc_3" class="form-control" id="etc_3" placeholder="비고 3 입력" value="{{ code.etc_3 }}">
            </div>
            <div class="form-group">
                <label for="alias_cd">대체 코드</label>
                <input name="alias_cd" class="form-control" id="alias_cd" placeholder="대체 코드 입력"
                       value="{{ code.alias_cd }}">
            </div>
            <div class="form-group">
                <label for="del_yn">삭제 여부</label>
                <select id="del_yn">
                    <option value="Y">Y</option>
                    <option value="N" selected="selected">N</option>
                </select>
            </div>
        {% endfor %}

    </div>

    {#        </form>#}


</div>
<!-- /.box-header -->

<!-- /.box-body -->

</div>

management/templates/code/common_code.html
{% extends "_layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% include 'code/code_list.html' %}
        </div>
        <div class="col-md-4">
            {% include 'code/code_put.html' %}

        </div>
        {% include 'eval_sheet/create_eval_sheet_modal.html' %}
    </div>
{% endblock %}