accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'accounts'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('change_password', change_password, name='change_password'),
    path('profile/<int:pk>', get_profile, name='profile', kwargs={'app_name': app_name, 'app_category_name': '개인정보', 'page_name': '프로필'}),
    path('profile/upload_img', upload_profile_image, name='upload_profile_image'),
    path('profile/clear_img', clear_profile_image, name='clear_profile_image')
]

evaluation/urls.py
from django.urls import path, re_path
from .views import *
from .views.eval_rel import *

app_name = 'evaluation'
app_category_name = "평가"

urlpatterns = [
    path('desc', evaluation_main, name='eval', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '역량평가'}),
    path('form/<int:pk>/', get_all_evaluation, name='eval_form', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '역량평가'}),
    path('form/<int:pk>/insert', insert_evaluation_form, name='eval_form_submit', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '역량평가'}),
    path('form/complete', complete_evaluation, name='eval_complete', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '역량평가'}),
    
    #평가 결과관리
    path('rslt', get_evaluation_rslt, name='eval_rslt', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가결과관리'}),
    path('rslt/rslt_excel_download', excel_download, name='rslt_excel_download'),

    # 평가 관계관리
    path('eRel/', get_eval_relation_main, name='eval_rel', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가관계관리'}),
    path('eRel/pjtAjax', get_erel_pjt_mem_list, name='rel_pjt_mem_ls'),
    path('eRel/treeAjax', get_erel_tree_mem_list, name='rel_tree_mem_ls'),

]

journal/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'journal'
app_category_name = "업무일지"

urlpatterns = [
    path('<int:pk>', get_all_journal, name='journal',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '업무일지'}),
]

management/urls.py
from django.urls import path, re_path
from management.views.pjt import (
    get_all_pjt, get_join_pjt_member, create_pjt_join_hist_member, delete_pjt_join_hist_member, create_pjt
    )
from management.views import code, code_list, code_add

app_name = 'management'

urlpatterns = [
    path('pjt/', get_all_pjt, name='pjt_list'),
    path('code/', code, name='code'),
    path('code/list', code_list, name='code_list'),
    path('code/add', code_add, name='code_add'),




    # ajax api
    path('pjtJoin/create/', create_pjt_join_hist_member, name='create_pjt_join_hist'),
    path('pjtJoin/delete/', delete_pjt_join_hist_member, name='del_pjt_join_hist'),
    path('pjtJoin/', get_join_pjt_member, name='join_pjt_mem'),
    path('pjt/create/', create_pjt, name='create_pjt')
    ]

mdm/urls.py
from django.urls import path, re_path
from mdm.views import *

from mdm.views.eval_plan import get_all_evaluation_plan, get_detail_eval_plan, save_eval_plan, del_eval_plan

app_name = 'mdm'
app_category_name = '기준정보 관리'

urlpatterns = [
    # 평가지 관리 메인 이동
    path('esheet/', sheet, name='eval_sheet',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가지관리'}),
    path('esheet/modal', modal, name="modal"),
    path('esheet/eval_ques', eval_ques_delete, name="eval_ques_delete"),
    path('esheet/eval_sheet', create_eval_sheet, name="eval_sheet_add"),

    # 평가항목 관리 메인 이동
    path('eitem/', get_all_evaluation_item, name='eval_item',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가항목관리'}),

    # 평가계획 관리 메인 이동
    path('eplan/', get_all_evaluation_plan, name='eval_plan',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가계획관리'}),
    
    # 비동기 요청
    path('ajax/test/', ajax_sample, name='ajax_sample'),
    path('eplan/detail/', get_detail_eval_plan, name='eplan_detail'),
    path('eplan/save', save_eval_plan, name='eplan_save'),

    # 평가문항 관리 메인 이동
    path('eques/', get_all_question, name='eval_ques', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가문항관리'}),
    path('eques/add', ajax_add_question, name='add_question'),
    path('eques/ques', get_question, name='get_question'),
    path('eques/save', save_question, name='save_question'),
    path('eques/eitem', ajax_get_eval_item, name='get_eval_item'),
    path('eplan/save/', save_eval_plan, name='eplan_save'),
    path('eplan/del/', del_eval_plan, name='eplan_del'),


]

templates/_footer.html
{% load static %}
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 0.1.1
    </div>
    <strong>Copyright 2023. Euclidsoft. All rights reserved.
</footer>

templates/_header.html
{% load static %}
<header class="main-header" data-spy="affix" data-offset-top="50">

    <!-- Logo -->
    <a href="{% url 'main' %}" class="logo">
        <span class="logo-mini"><b>E</b>S</span>
        <span class="logo-lg"><img src="{% static 'img/logo/logo.png' %}"/></span>
    </a>
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img
                                    {% if mem_detail.profile_img %}
                                        src="{{ mem_detail.profile_img.url|default:'' }}"
                                    {% else %}
                                        src="/media/profile/default_avatar.png"
                                    {% endif %}
                                        class="user-image" alt="User Image"/>
                            <span class="hidden-xs">{{ request.session.posi_nm }}</span> &nbsp;
                            <strong class="hidden-xs">{{ user.name }}</strong>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img
                                        {% if mem_detail.profile_img %}
                                            src="{{ mem_detail.profile_img.url|default:'' }}"
                                        {% else %}
                                            src="/media/profile/default_avatar.png"
                                        {% endif %}

                                            class="img-circle" alt="User Image"/>

                                <p>
                                    {{ user.name }}
                                    <small>{{ user.email }}</small>
                                </p>
                            </li>

                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'accounts:profile' user.id %}"
                                       class="btn btn-default btn-flat">프로필</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'accounts:logout' %}" class="btn btn-default btn-flat">로그아웃</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                {% endif %}

            </ul>
        </div>
    </nav>

</header>

templates/_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    {% include '_meta.html' %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    {% include '_header.html' %}
    {% include '_left_aside.html' %}
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ page_name }}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'main' %}"><i class="fa fa-home"></i> Home</a></li>
                <li class="active">{{ app_category_name }} / {{ page_name }}</li>
            </ol>
        </section>
        <section class="content">
            {% block content %}
            {% endblock %}
        </section>
    </div>
    {% include '_footer.html' %}
    <div class="control-sidebar-bg"></div>
</div>
</body>
</html>

templates/_left_aside.html
{% load static %}
{% load common_tags %}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img
                        {% if mem_detail.profile_img %}
                            src="{{ mem_detail.profile_img.url|default:'' }}"
                        {% else %}
                            src="/media/profile/default_avatar.png"
                        {% endif %}

                            class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p>{{ user.name }}</p>
                <span class="text-gray">{{ request.session.duty_resp_nm }}</span>
                {#                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>#}
            </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            {% if user|has_groups:"일반사원" %}
                <li class="header">평가</li>
                <li><a href="{% url 'evaluation:eval' %}"><i class="fa fa-edit"></i> <span>역량평가</span></a></li>
                <li class="header">업무일지</li>
                <li><a href="{% url 'journal:journal' user.id %}"><i class="fa fa-calendar"></i> <span>업무일지</span></a></li>
            {% endif %}

            {% if user|has_groups:"인사관리자" %}
                <li class="header">기준정보 관리</li>

                <li><a href="{% url 'evaluation:eval_rel' %}"><i class="fa fa-users"></i> <span>평가관계관리</span></a></li>
                <li><a href="/admin/mdm/evalitem/"><i class="fa fa-tag"></i> <span>평가항목관리</span></a></li>
                <li><a href="{% url 'mdm:eval_ques' %}"><i class="fa fa-tags"></i> <span>평가문항관리</span></a></li>
                <li><a href="{% url 'mdm:eval_sheet' %}"><i class="fa fa-list-ol"></i> <span>평가지관리</span></a></li>
                <li><a href="{% url 'mdm:eval_plan' %}"><i class="fa fa-calendar-check-o"></i> <span>평가계획관리</span></a></li>
                <li><a href="{% url 'evaluation:eval_rslt' %}"><i class="fa fa-list-alt"></i> <span>평가결과관리</span></a></li>
{#                <li><a href="#"><i class="fa fa-circle-o"></i> <span>업무일지관리</span></a></li>#}
            {% endif %}
            {% if user|has_groups:"인사관리자" or user|has_groups:"시스템관리자" or user|has_groups:"관리자" %}
                <li class="header">시스템 관리</li>
                {#                <li><a href="#"><i class="fa fa-users"></i> <span>회원관리</span></a></li>#}
                <li><a href="/admin/accounts/eusomem/"><i class="fa fa-user"></i> <span>회원 관리</span></a>
                <li><a href="{% url 'management:pjt_list' %}"><i class="fa fa-suitcase"></i> <span>프로젝트 관리</span></a>
                </li>
                <li><a href="{% url 'management:code' %}"><i class="fa fa-code"></i> <span>공통코드관리</span></a></li>
            {% endif %}
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

templates/_login_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Euclidsoft | Log in</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
</head>
<body class="hold-transition login-page">
{% block content %}
{% endblock %}

<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
{% block java_script %}
{% endblock %}
</body>
</html>

templates/_meta.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Euclidsoft</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/flat/blue.css' %}">
<!-- Morris chart -->
<link rel="stylesheet" href="{% static 'plugins/morris/morris.css' %}">
<!-- jvectormap -->
<link rel="stylesheet" href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
<!-- Date Picker -->
<link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/all.css' %}">


<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{% static 'plugins/morris/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
<script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>

{#Datatable#}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css'%}">

{#alert#}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>

<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>

<script src="{% static 'js/app.min.js' %}"></script>


{#<script src="{% static 'js/pages/dashboard.js' %}"></script>#}

<script src="{% static 'js/demo.js' %}"></script>

<script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>

<!-- iCheck 1.0.1 -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>

templates/_metal.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>AdminLTE 2 | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/flat/blue.css' %}">
<!-- Morris chart -->
<link rel="stylesheet" href="{% static 'plugins/morris/morris.css' %}">
<!-- jvectormap -->
<link rel="stylesheet" href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
<!-- Date Picker -->
<link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{% static 'plugins/morris/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/app.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'js/demo.js' %}"></script>

templates/_right_aside.html
{% load static %}
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>

templates/main.html
{% extends "_layout.html" %}
{% block content %}
    <h1>메인 페이지</h1>
    <a href="{% url 'management:code' %}">코드목록</a>
{% endblock %}