management/urls.py
from django.urls import path, re_path
from management.views.pjt import (
    get_all_pjt, get_join_pjt_member, create_pjt_join_hist_member, delete_pjt_join_hist_member, create_pjt
    )
from management.views import code, code_list, code_add

app_name = 'management'

urlpatterns = [
    path('pjt/', get_all_pjt, name='pjt_list'),
    path('code/', code, name='code'),
    path('code/list', code_list, name='code_list'),
    path('code/add', code_add, name='code_add'),




    # ajax api
    path('pjtJoin/create/', create_pjt_join_hist_member, name='create_pjt_join_hist'),
    path('pjtJoin/delete/', delete_pjt_join_hist_member, name='del_pjt_join_hist'),
    path('pjtJoin/', get_join_pjt_member, name='join_pjt_mem'),
    path('pjt/create/', create_pjt, name='create_pjt')
    ]

mdm/urls.py
from django.urls import path, re_path
from mdm.views import *

from mdm.views.eval_plan import get_all_evaluation_plan, get_detail_eval_plan, save_eval_plan, del_eval_plan

app_name = 'mdm'
app_category_name = '기준정보 관리'

urlpatterns = [
    # 평가지 관리 메인 이동
    path('esheet/', sheet, name='eval_sheet',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가지관리'}),
    path('esheet/modal', modal, name="modal"),
    path('esheet/eval_ques', eval_ques_delete, name="eval_ques_delete"),
    path('esheet/eval_sheet', create_eval_sheet, name="eval_sheet_add"),

    # 평가항목 관리 메인 이동
    path('eitem/', get_all_evaluation_item, name='eval_item',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가항목관리'}),

    # 평가계획 관리 메인 이동
    path('eplan/', get_all_evaluation_plan, name='eval_plan',
         kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가계획관리'}),
    
    # 비동기 요청
    path('ajax/test/', ajax_sample, name='ajax_sample'),
    path('eplan/detail/', get_detail_eval_plan, name='eplan_detail'),
    path('eplan/save', save_eval_plan, name='eplan_save'),

    # 평가문항 관리 메인 이동
    path('eques/', get_all_question, name='eval_ques', kwargs={'app_name': app_name, 'app_category_name': app_category_name, 'page_name': '평가문항관리'}),
    path('eques/add', ajax_add_question, name='add_question'),
    path('eques/ques', get_question, name='get_question'),
    path('eques/save', save_question, name='save_question'),
    path('eques/eitem', ajax_get_eval_item, name='get_eval_item'),
    path('eplan/save/', save_eval_plan, name='eplan_save'),
    path('eplan/del/', del_eval_plan, name='eplan_del'),


]

management/models.py
from django.db import models
from accounts.models import EusoMem


# Create your models here.
class CommCd(models.Model):
    comm_cd = models.CharField(primary_key=True, max_length=10)
    hi_comm_cd = models.CharField(max_length=10, blank=True, null=True)
    cd_nm = models.CharField(max_length=100)
    cd_desc = models.CharField(max_length=200, blank=True, null=True)
    etc_1 = models.CharField(max_length=100, blank=True, null=True)
    etc_2 = models.CharField(max_length=100, blank=True, null=True)
    etc_3 = models.CharField(max_length=100, blank=True, null=True)
    alias_cd = models.CharField(max_length=10, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comm_cd'


class ZipCd(models.Model):
    zip_no = models.CharField(primary_key=True, max_length=6)
    sido = models.CharField(max_length=20, blank=True, null=True)
    sigungu = models.CharField(max_length=20, blank=True, null=True)
    eupmyun = models.IntegerField(blank=True, null=True)
    doro_cd = models.IntegerField(blank=True, null=True)
    doro_nm = models.CharField(max_length=80, blank=True, null=True)
    build_no1 = models.IntegerField(blank=True, null=True)
    build_no2 = models.IntegerField(blank=True, null=True)
    build_nm = models.CharField(max_length=200, blank=True, null=True)
    dong_cd = models.CharField(max_length=10, blank=True, null=True)
    dong_nm = models.CharField(max_length=20, blank=True, null=True)
    ri = models.CharField(max_length=20, blank=True, null=True)
    h_dong_nm = models.CharField(max_length=20, blank=True, null=True)
    zibun1 = models.IntegerField(blank=True, null=True)
    zibun2 = models.IntegerField(blank=True, null=True)
    zip_no_old = models.CharField(max_length=6, blank=True, null=True)
    zip_sn = models.CharField(max_length=3, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True)
    modf_dt = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'zip_cd'


class CsOrgn(models.Model):
    cs_no = models.AutoField(primary_key=True)
    zip_no = models.ForeignKey('ZipCd', models.DO_NOTHING, blank=True, null=True, db_column='zip_no')
    cs_nm = models.CharField(max_length=100, blank=True, null=True)
    orgn_reg_no = models.CharField(max_length=13, blank=True, null=True)
    busir_no = models.CharField(max_length=10, blank=True, null=True)
    tel_no = models.CharField(max_length=12, blank=True, null=True)
    fax_no = models.CharField(max_length=12, blank=True, null=True)
    cs_addr = models.CharField(max_length=100, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'cs_orgn'


class EusoPjt(models.Model):
    pjt_no = models.AutoField(primary_key=True)
    cs_no = models.ForeignKey(CsOrgn, models.DO_NOTHING, db_column='cs_no')
    pjt_nm = models.CharField(max_length=100, blank=True, null=True)
    start_dt = models.DateField(max_length=8, blank=True, null=True)
    end_dt = models.DateField(max_length=8, blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    del_yn = models.CharField(max_length=1, default="N", blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'euso_pjt'


class PjtJoinHist(models.Model):
    join_hist_no = models.AutoField(primary_key=True)
    pjt_no = models.ForeignKey(EusoPjt, models.DO_NOTHING, db_column='pjt_no')
    mem_no = models.ForeignKey(EusoMem, models.DO_NOTHING, db_column='mem_no')
    role_cd = models.CharField(max_length=10, blank=True, null=True)
    enter_dt = models.DateField(max_length=8, blank=True, null=True)
    out_dt = models.DateField(max_length=8, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True)
    modf_mem_no = models.IntegerField(blank=True, null=True)
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    del_yn = models.CharField(max_length=1, default='N', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'pjt_join_hist'


class EusoDept(models.Model):
    dept_no = models.AutoField(primary_key=True)
    dept_cd = models.CharField(max_length=10, blank=True, null=True)
    hi_dept_no = models.IntegerField(blank=True, null=True)
    dept_nm = models.CharField(max_length=50, blank=True, null=True)
    reg_mem_no = models.IntegerField(blank=True, null=True, verbose_name='등록 회원ID')
    modf_mem_no = models.IntegerField(blank=True, null=True, verbose_name='수정자 ID')
    reg_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modf_dt = models.DateTimeField(blank=True, null=True, auto_now=True)
    del_yn = models.CharField(max_length=1, blank=True, null=True)


    class Meta:
        managed = True
        db_table = 'euso_dept'
        verbose_name = '부서'

management/views/code.py
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser
from django.shortcuts import render, redirect
from rest_framework.response import Response
from django.urls import reverse
from management.serializers import *


@api_view(['POST', 'GET', 'DELETE'])
@permission_classes([IsAuthenticated, IsAdminUser])
@csrf_exempt
def code(req):
    test = req.data.copy()
    test['reg_mem_no'] = req.user.id
    if req.method == 'GET':
        codes = CommCd.objects.all()
        # codes = ABCD.objects.filter(del_yn='N')
        serializer = CommCdSerializer(codes, many=True)
        listt = {
            'comm_cd': "",
        }
        return render(req, 'code/common_code.html', {'code_list': serializer.data, 'list': listt})
    if req.method == 'DELETE':
        try:
            old_id = test['comm_cd']
            print(test)
            test['modf_mem_no'] = req.user.id
            obj = CommCd.objects.get(comm_cd=old_id)
            serializer = CommCdSerializer(obj, data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            req.method = 'GET'
            return Response(status=status.HTTP_204_NO_CONTENT)
        except:
            return Response(status=status.HTTP_410_GONE)

    if req.method == 'POST':
        try:
            old_id = test['comm_cd']
            test['modf_mem_no'] = req.user.id

            obj = CommCd.objects.get(comm_cd=old_id)  # 존재하지않으면 doesnotexist 예외처리 -> except구문
            # obj가 존재하는 경우 == 이미 있는 코드 => 수정 로직
            serializer = CommCdSerializer(obj, data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            return redirect(reverse('management:code'), req)
        except:
            test['modf_mem_no'] = req.user.id

            serializer = CommCdSerializer(data=test, partial=True)
            serializer.is_valid()
            serializer.save()
            return redirect(reverse('management:code'), req)


@api_view(['GET'])
@permission_classes([IsAuthenticated, IsAdminUser])
@csrf_exempt
def code_list(req):
    comm_cd = req.GET['comm_cd']
    data = CommCd.objects.filter(comm_cd=comm_cd)
    serializer = CommCdSerializer(data, many=True)
    return render(req, 'code/code_put.html', {'list': serializer.data, })


@api_view(['GET'])
@permission_classes([IsAuthenticated, IsAdminUser])
def code_add(req):
    listt = {
        'comm_cd': "",
    }
    return render(req, 'code/code_put.html', {'list': listt})

management/views/pjt.py
from rest_framework import status
from datetime import datetime
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.shortcuts import render, redirect

from management.models import EusoPjt, CommCd, PjtJoinHist, CsOrgn
from accounts.models import EusoMem

from management.serializers import (
    EusoPjtSerializer, CommCdMapperSerializer, GetPjtJoinMemberSerializer, CreatePjtJoinMemberSerializer,
    DelPjtJoinMemberSerializer, GetCsOrgnSerializer, CreatePjtSerializer
    )
from accounts.serializers import GetEusoMemSerializer


@api_view(['GET'])
@permission_classes([AllowAny])
def get_all_pjt(requests):
    # 프로젝트 목록 가져오기
    pjt_obj = EusoPjt.objects.all().order_by('-start_dt')
    pjt_serializer = EusoPjtSerializer(pjt_obj, many=True)

    # 기관 목록 가져오기
    cs_obj = CsOrgn.objects.filter(del_yn='N')
    cs_serializer = GetCsOrgnSerializer(cs_obj, many=True)
    return render(requests, 'pjt/pjt_main.html', {'pjt_list': pjt_serializer.data, 'cs_ls': cs_serializer.data})


@api_view(['POST'])
@permission_classes([AllowAny])
def create_pjt(requests):
    req = requests.data

    date_range = [date.strip() for date in req['date_range'].split('-')]
    start_dt = datetime.strptime(date_range[0], '%m/%d/%Y')
    end_dt = datetime.strptime(date_range[1], '%m/%d/%Y')

    pjt_dic = {
        "pjt_nm": req["pjt_nm"],
        "cs_no": req["cs_no"],
        "start_dt": start_dt,
        "end_dt": end_dt,
        "reg_mem_no": requests.user.id,
        "modf_mem_no": requests.user.id
    }
    pjt_serializer = CreatePjtSerializer(data=pjt_dic)
    if pjt_serializer.is_valid():
        pjt_serializer.save()

        return redirect("/manage/pjt/")

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_serializer.errors})


@api_view(["POST", "GET"])
@permission_classes([AllowAny])
def get_join_pjt_member(requests):
    pjt_no = requests.data["pjt_no"]

    # 회원 목록 가져오기
    euso_mem_qs = EusoMem.objects.filter(del_yn="N")
    euso_mem_serializer = GetEusoMemSerializer(euso_mem_qs, many=True)

    # 프로젝트 역할 코드 가져오기
    role_cd_qs = CommCd.objects.filter(hi_comm_cd='CC004000', del_yn='N')
    role_cd_serializer = CommCdMapperSerializer(role_cd_qs, many=True)

    # 프로젝트 참여중인 회원 목록 가져오기
    pjt_join_hist_qs = PjtJoinHist.objects.filter(pjt_no=pjt_no, del_yn='N')
    pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_qs, many=True)
    return render(requests, 'pjt/pjt_join_mem.html', {'role_list': role_cd_serializer.data,
                                                     'pjt_no': pjt_no,
                                                     'mem_ls': euso_mem_serializer.data,
                                                     'pjt_mem_ls': pjt_join_hist_serializer.data,
                                                     })


@api_view(["POST"])
@permission_classes([AllowAny])
def create_pjt_join_hist_member(requests):
    req = requests.data.copy()

    date_range = [date.strip() for date in req['date_range'].split('-')]
    enter_dt = datetime.strptime(date_range[0], '%m/%d/%Y').strftime("%Y-%m-%d")
    out_dt = datetime.strptime(date_range[1], '%m/%d/%Y').strftime("%Y-%m-%d")

    print(enter_dt)
    print(out_dt)

    pjt_join_hist_dic = {
        "pjt_no": req['pjt_no'],
        "mem_no": req['mem_no'],
        "role_cd": req['role_cd'],
        "enter_dt": enter_dt,
        "out_dt": out_dt,
        "reg_mem_no": requests.user.id,
        "modf_mem_no": requests.user.id
    }

    pjt_join_hist_serializer = CreatePjtJoinMemberSerializer(data=pjt_join_hist_dic)
    if pjt_join_hist_serializer.is_valid():
        pjt_join_hist_serializer.save()

        # 프로젝트 참여중인 회원 목록 가져오기
        pjt_join_hist_obj = PjtJoinHist.objects.filter(pjt_no=req['pjt_no'], del_yn='N')
        pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_obj, many=True)
        return render(requests, 'pjt/pjt_mem_ls_form.html', {"pjt_mem_ls": pjt_join_hist_serializer.data})

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_join_hist_serializer.errors})


@api_view(["POST"])
@permission_classes([AllowAny])
def delete_pjt_join_hist_member(requests):
    req = requests.data.copy()

    pjt_join_hist_dic = {
        "join_hist_no": req['join_hist_no'],
        "mem_no": req['mem_no'],
        "del_yn": "Y",
        "modf_mem_no": requests.user.id
    }

    pjt_join_hist_qs = PjtJoinHist.objects.get(join_hist_no=req['join_hist_no'])
    pjt_join_hist_serializer = DelPjtJoinMemberSerializer(pjt_join_hist_qs, data=pjt_join_hist_dic)

    if pjt_join_hist_serializer.is_valid():
        pjt_join_hist_serializer.save()

        # 프로젝트 참여중인 회원 목록 가져오기
        pjt_join_hist_qs = PjtJoinHist.objects.filter(pjt_no=req['pjt_no'], del_yn='N')
        pjt_join_hist_serializer = GetPjtJoinMemberSerializer(pjt_join_hist_qs, many=True)
        return render(requests, 'pjt/pjt_mem_ls_form.html', {"pjt_mem_ls": pjt_join_hist_serializer.data})

    else:
        return render(requests, 'pjt/pjt_error_form.html', {"error": pjt_join_hist_serializer.errors})

management/templates/pjt/add_pjt_modal.html
<!-- 프로젝트 추가 모달 -->
    <div class="modal fade" id="AddPjtModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><strong>프로젝트 추가</strong></h4>
                </div>

                <div class="modal-body">
                    <form class="form-horizontal" id="add_pjt">
                        {% csrf_token %}
                        <div class="box-body">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">프로젝트 이름</label>
                                <div class="input-group col-sm-8">
                                    <input type="text" class="form-control" placeholder="프로젝트 이름을 입력해주세요" name="pjt_nm">
                                </div>
                            </div>

                            <!-- 기관 입력 -->
                            <div class="form-group">
                                <label class="col-sm-2 control-label">기관 이름</label>
                                <div class="input-group">
                                    <select id="cs_ls" class="form-control select2" style="width: 60rem" name="cs_no">
                                        {%  for cs in cs_ls %}
                                        <option value="{{ cs.cs_no }}" >
                                            {{ cs.cs_nm }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">시작 및 종료일</label>

                                <div class="input-group col-sm-8">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" class="form-control pull-right" id="reservation2" name="date_range">
                                </div>
                            </div>
                        </div>

                        <div class="modal-footer" style="padding-bottom: 0">
                            <button type="button" class="btn btn-default" data-dismiss="modal">취소</button>
                            <button type="submit" class="btn btn-primary">저장</button>
                        </div>
                    </form>
                <div id="pjtErrorBox"></div>
                </div>
            </div>
        </div>
    </div>
<script>
    $("#add_pjt").submit(function( event ) {
        $.ajaxSetup({
            headers: { 'X-CSRFToken': '{{ csrf_token }}' }
        })

        let data = $(this).serializeArray()
        console.log(data)

        $.ajax({
            url: "{% url 'management:create_pjt' %}",
            type: 'POST',
            datatype: 'json',
            data: data
            })
            .done(function () {})
            .fail(function (xhr, status, errorThrown, html) {
                $('#pjtErrorBox').html(html)
                }
            )
    })

    $(function () {
        $("#cs_ls").select2();
    })


</script>

management/templates/pjt/pjt_error_form.html
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h5><i class="icon fa fa-ban"></i> {{ error }}</h5>
</div>

management/templates/pjt/pjt_join_mem.html
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title" id="join_pjt_nm">
                    <strong>프로젝트 참여 등록</strong>
                </h3>
            </div>

            <form class="form-horizontal" id="join_pjt_form">
                {% csrf_token %}
                <div class="box-body">
                    <!-- pjt_no hidden -->
                    <input type="hidden" value="{{ pjt_no }}" id="pjt_no" name="pjt_no">

                    <!-- 프로젝트 참여 인원 입력 -->
                    <div class="form-group">
                        <label class="col-sm-2 control-label">이름</label>
                        <div class="input-group col-sm-8 ">
                            <select id="mem_ls" class="form-control" name="mem_no">
                                {%  for mem in mem_ls %}
                                <option value="{{ mem.id }}">
                                    {{ mem.name }}   {{ mem.posi_nm }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <!-- 프로젝트 내 역할 입력 -->
                    <div class="form-group">
                        <label class="col-sm-2 control-label">역할</label>
                        <div class="input-group col-sm-8">
                            <select class="form-control" name="role_cd">
                                {% for role in role_list %}
                                <option value="{{ role.comm_cd }}">{{ role.cd_nm }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <!-- 참여 시작 및 종료일 입력 -->
                    <div class="form-group">
                        <label class="col-sm-2 control-label">참여 시작 및 종료일</label>

                        <div class="input-group col-sm-8">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="reservation" name="date_range">
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-success pull-right">저장</button>
                </div>

            </form>
        </div>

        <div id="error_box"></div>


        <div class="box" id="added_pjt_mem_ls">
            {% include 'pjt/pjt_mem_ls_form.html' %}
        </div>
<script>
    $( "#join_pjt_form" ).submit(function( event ) {
        event.preventDefault();
        $.ajaxSetup({
            headers: { "X-CSRFToken": '{{csrf_token}}' }
        })

        let data = $(this).serializeArray();
        data = data.concat([{pjt_no: {{ pjt_no }}}])
        console.log(data)

        $.ajax({
            url: "{% url 'management:create_pjt_join_hist' %}",
            type: "POST",
            datatype: "json",
            data: data
            })
            .done(function (html) {
                $('#added_pjt_mem_ls').html(html)
            })
            .fail(function (xhr, status, errorThrown, html) {
                $('#error_box').html(html)
                }
            )
    })

    function memDelete(join_hist_no, pjt_no, mem_no) {
        $.ajaxSetup({
            headers: { "X-CSRFToken": '{{csrf_token}}' }
            })


        $.ajax({
            url: "{% url 'management:del_pjt_join_hist' %}",
            type: "POST",
            datatype: "json",
            data: {
                join_hist_no: join_hist_no,
                pjt_no: pjt_no,
                mem_no: mem_no
                }
            })
            .done(function (html) {
                $('#added_pjt_mem_ls').html(html)
            })
            .fail(function (xhr, status, errorThrown, html) {
                $('#error_box').html(html)
                }
            )
    }


    $(function () {
        //Initialize Select2 Elements
        $("#mem_ls").select2();
            //Date range picker
        $('#reservation').daterangepicker();

    })
</script>

management/templates/pjt/pjt_main.html
{% extends "_layout.html" %}

{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h2 class="box-title">
                        <strong>유클리드 프로젝트</strong>
                    </h2>
                    <button type="button" class="btn btn-default btn-sm pull-right" data-toggle="modal" data-target="#AddPjtModal" style="cursor: pointer;">
                        추가
                    </button>
                </div>

                <div class="box-body">
                    <table class="table table-hover">
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>프로젝트 이름</th>
                            <th>프로젝트 기간</th>
                        </tr>
                        {% for pjt in pjt_list %}
                        <tr onclick="doJoinPjtDisplay({{ pjt.pjt_no }})" style="cursor: pointer">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ pjt.pjt_nm }}</td>
                            <td>{{ pjt.start_dt }} ~ {{ pjt.end_dt }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>

                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="#">&laquo;</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-8" id="join_pjt">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title" id="join_pjt_nm">
                        <strong>프로젝트 참여 등록</strong>
                    </h3>
                </div>
                <div class="alert alert-info alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fa fa-info"></i> 프로젝트를 선택해주세요</h5>
                </div>
            </div>
        </div>

        {% include 'pjt/add_pjt_modal.html' %}

    </div>
</section>


<script>
    function doJoinPjtDisplay(pjtNo) {
        $.ajaxSetup({
            headers: { "X-CSRFToken": '{{csrf_token}}' }
        });

        $.ajax({
            url: "{% url 'management:join_pjt_mem' %}",
            type: "POST",
            datatype: "json",
            data: {
                pjt_no: pjtNo
                }
            })
            .done(function (html) {
                    $('#join_pjt').html(html)
            })
            .fail(function (xhr, status, errorThrown) {
                $('#error_box').html("오류 발생. <br>")
                    .append("오류명: " + errorThrown)
                }
            )
    }


    $('#AddPjtModal').on('shown.bs.modal', function () {
      $('#AddPjtModal').focus()
    })


    $(function () {
            //Date range picker
        $('#reservation').daterangepicker();
        $('#reservation2').daterangepicker();

    })
</script>
{% endblock %}

management/templates/pjt/pjt_mem_ls_form.html
<div class="box-header">
    <h3 class="box-title">
        <strong>프로젝트 참여 인원</strong>
    </h3>
</div>

<div class="box-body no-padding">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>이름</th>
                <th>역할</th>
                <th>프로젝트 참여기간</th>
                <th style="width: 70px"></th>
            </tr>
        </thead>
        <tbody>
            {% for mem in pjt_mem_ls %}
                <tr>
                    <th name="join_hist_no">{{ forloop.counter }}</th>
                    <th name="mem_nm">{{ mem.mem_nm }}</th>
                    <th name="role_nm">{{ mem.role_nm }}</th>
                    <th name="date_range">{{ mem.enter_dt }} ~ {{ mem.out_dt }}</th>
                    <th><button type="button" onclick="memDelete({{ mem.join_hist_no }}, {{ mem.pjt_no }}, {{ mem.mem_no }})" class="btn-danger btn-sm pull-right">삭제</button></th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>